# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: text_analyzer.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13text_analyzer.proto\x12\rtext_analyzer\"\r\n\x0bWordRequest\"\xd7\x01\n\x10\x41nalysisResponse\x12\x17\n\x0f\x61vg_word_length\x18\x01 \x01(\x02\x12\x1b\n\x13\x61vg_sentence_length\x18\x02 \x01(\x02\x12S\n\x13\x61rchaic_word_counts\x18\x03 \x03(\x0b\x32\x36.text_analyzer.AnalysisResponse.ArchaicWordCountsEntry\x1a\x38\n\x16\x41rchaicWordCountsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\x32\\\n\x0cTextAnalysis\x12L\n\x0b\x41nalyzeWord\x12\x1a.text_analyzer.WordRequest\x1a\x1f.text_analyzer.AnalysisResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'text_analyzer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ANALYSISRESPONSE_ARCHAICWORDCOUNTSENTRY']._loaded_options = None
  _globals['_ANALYSISRESPONSE_ARCHAICWORDCOUNTSENTRY']._serialized_options = b'8\001'
  _globals['_WORDREQUEST']._serialized_start=38
  _globals['_WORDREQUEST']._serialized_end=51
  _globals['_ANALYSISRESPONSE']._serialized_start=54
  _globals['_ANALYSISRESPONSE']._serialized_end=269
  _globals['_ANALYSISRESPONSE_ARCHAICWORDCOUNTSENTRY']._serialized_start=213
  _globals['_ANALYSISRESPONSE_ARCHAICWORDCOUNTSENTRY']._serialized_end=269
  _globals['_TEXTANALYSIS']._serialized_start=271
  _globals['_TEXTANALYSIS']._serialized_end=363
# @@protoc_insertion_point(module_scope)
